@startuml

Title: ACS on AWS Helm Deployment Overview

skinparam componentStyle uml2
skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
    FontSize 15
    FontStyle none
}

actor Client

node "nginx-ingress namespace" {
    component "NGINX ingress-controller" as nginx #lightgrey
}

node "ACS namespace" {
    component "Alfresco Digital Workspace" as adw #lightgrey
    component "Alfresco Content Services" as acs #lightgrey
    component "Alfresco Search Services" as ass #lightgrey
    component "Alfresco Share" as share #lightgrey
    rectangle "Alfresco Transform Service" {
        component "Transform Router" as tr #lightgrey
        component "Shared File Store" as sfs #lightgrey
        component "Alfresco PDF Renderer" as pdfr #lightgrey
        component "LibreOffice" as libr #lightgrey
        component "ImageMagick" as img #lightgrey
        component "Tika" as tika #lightgrey
    }
}

cloud "Amazon Web Services" {
    storage "S3" as s3
    database "Aurora RDS" as db
    storage "EBS" as ebs
    storage "EFS Volume Claim" as vc
    queue "Amazon MQ" as mq

}

Client --> nginx

nginx --> acs
nginx --> share
nginx --> adw

acs --> vc
ass --> ebs
sfs --> vc
acs --> s3

ass <--> acs
acs --> db
acs --> pdfr
acs --> libr
acs --> img
acs --> tika
acs --> sfs
acs <--> mq
tr -up-> pdfr
tr -up-> libr
tr -up-> img
tr -up-> tika
tr <--> mq
pdfr --> sfs
libr --> sfs
img --> sfs
tika --> sfs
share --> acs

center footer Copyright 2019 Alfresco Software Inc

@enduml
