@startuml

Title: ACS on AWS Helm Deployment Overview

skinparam componentStyle uml2
skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
    FontSize 15
    FontStyle none
}

actor Client

node "nginx-ingress namespace" {
    component "NGINX ingress-controller" as nginx #lightgrey
}

node "ACS namespace" {
    component "Alfresco Digital Workspace" as adw #lightgrey
    component "Alfresco Content Services" as acs #lightgrey
    component "Alfresco Search Services" as ass #lightgrey
    component "Alfresco Share" as share #lightgrey
    database "EFS Volume Claim" as vc
    rectangle "Alfresco Transform Service" {
        component "Transform Router" as tr #lightgrey
        component "Shared File Store" as sfs #lightgrey
        component "ActiveMQ" as amq #lightgrey
        component "Alfresco PDF Renderer" as pdfr #lightgrey
        component "LibreOffice" as libr #lightgrey
        component "ImageMagick" as img #lightgrey
        component "Tika" as tika #lightgrey
    }
}

database "Aurora RDS" as db
database "S3" as s3

Client --> nginx

nginx --> acs
nginx --> share
nginx --> adw

acs --> vc
ass --> vc
sfs --> vc
acs --> s3

ass <--> acs
acs --> db
acs --> pdfr
acs --> libr
acs --> img
acs --> tika
acs --> sfs
acs <--> amq
tr --> pdfr
tr --> libr
tr --> img
tr --> tika
tr <-up-> amq
pdfr --> sfs
libr --> sfs
img --> sfs
tika --> sfs
share --> acs

center footer Copyright 2018 Alfresco Software Inc

@enduml
