@startuml

Title: Helm Deployment Overview

skinparam componentStyle uml2
skinparam linetype ortho

actor Client

node "Helm Chart" {
    component "NGINX proxy" as nginx #lightgrey
    component "Alfresco Content Services" as acs #lightgrey
    component "Alfresco Search Services" as ass #lightgrey
    component "PostgreSQL" as psql #lightgrey
    component "Alfresco PDF Renderer" as pdfr #lightgrey
    component "LibreOffice" as libr #lightgrey
    component "ImageMagick" as img #lightgrey
    component "Alfresco Share" as share #lightgrey
    database "Volume Claim" as vc
}

Client --> nginx

nginx --> acs
nginx --> ass
nginx --> share

acs --> vc
ass --> vc
psql --> vc

ass --> acs
acs --> psql
acs --> pdfr
acs --> libr
acs --> img
share --> acs

center footer Copyright 2018 Alfresco Software Inc

@enduml