@startuml

Title: Docker Compose Deployment Overview (Community)

skinparam componentStyle uml2
skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
    FontSize 15
    FontStyle none
}

actor Client

node "Docker Compose" {
    component "NGINX proxy" as proxy #lightgrey
    component "Alfresco Content Services" as acs #lightgrey
    component "Alfresco Admin Console" as aac #lightgrey
    component "Alfresco Search Services" as ass #lightgrey
    component "PostgreSQL" as psql #lightgrey
    component "Alfresco Share" as share #lightgrey
    component "ActiveMQ" as amq #lightgrey
    component "Transform Core (AIO)" as tcore #lightgrey
    component "Alfresco Content App" as aca #lightgrey
}

Client --> proxy

proxy --> aac
proxy --> share
proxy --> aca
proxy --> acs

acs <-left-> ass
acs --> psql
acs --> tcore
acs <-left-> amq
share -left-> acs

center footer Copyright 2022 Alfresco Software Inc

@enduml
