@startuml Component Persistence Diagram
'!theme crt-amber
title Component Persistence

skinparam linetype ortho

start
:Read .Values.component.persistence;
if (.enabled?) then (yes)
  if(.existingClaim?) then (yes)
    :Render deployment with Persistent volume
    backed by existingClaim PVC;
  else (no)
    :Create PVC;
    if(.StorageClass?) then (yes)
      :Use provided storageClass
      for dynamic provisioning of PV;
    else (no)
      :Use default storageClass
      for dynamic provisioning of PV;
    endif
    :Render deployment with Persistent volume
    backed by created PVC;
  endif
else (no)
  :Render deployment
  with Ephemeral volume (emptyDir);
endif
stop

center footer Copyright 2022 Alfresco Software Inc
@enduml
