@startuml

Title: ACS Enterprise on EKS Helm Deployment Overview

skinparam componentStyle uml2
skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
    FontSize 15
    FontStyle none
}

actor Client

node "alfresco namespace" {
    component "NGINX ingress-controller" as nginx #lightgrey
    together {
        component "Alfresco Digital Workspace" as adw #lightgrey
        component "Alfresco Share" as share #lightgrey
    }
    component "Alfresco Content Services" as acs #lightgrey
    component "Alfresco Search Services" as ass #lightgrey
    component "Alfresco Sync Service" as sync #lightgrey
    component "PostgreSQL" as psql #lightgrey
    component "ActiveMQ" as amq #lightgrey
    rectangle "Alfresco Transform Service" as ats {
        component "Transform Router" as tr #lightgrey
        component "Shared File Store" as sfs #lightgrey
        component "Alfresco PDF Renderer" as pdfr #lightgrey
        component "LibreOffice" as libr #lightgrey
        component "ImageMagick" as img #lightgrey
        component "Tika" as tika #lightgrey
        component "TransformMisc" as misc #lightgrey
    }
}

cloud "Amazon Web Services" {
    rectangle "GP2/3" {
        storage "EBS" as ebs1
        storage "EBS" as ebs2
        storage "EBS" as ebs3
    }
    rectangle "EFS CSI" {
        storage "EFS Volume" as vc
    }
}

Client -->> nginx

nginx -->> acs
nginx -->> share
nginx -->> adw

acs -[hidden]- ats
acs -->> vc
amq -->> ebs1
psql -->> ebs2
sfs -->> vc
ass -->> ebs3

acs -->> psql
acs -->> pdfr
acs -->> libr
acs -->> img
acs -->> tika
acs -->> misc
acs -->> sfs
acs <<-->> amq
tr -->> pdfr
tr -->> libr
tr -->> img
tr -->> tika
tr -->> misc
tr <<-->> amq
pdfr -->> sfs
libr -->> sfs
img -->> sfs
tika -->> sfs
misc -->> sfs
share -->> acs
adw ->> acs

acs <<->> ass
sync <<->> acs
sync -->> psql
sync -->> amq

center footer Copyright 2021 Alfresco Software Inc

@enduml
