@startuml

Title: ACS Community on EKS Helm Deployment Overview

skinparam componentStyle uml2
skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
    FontSize 15
    FontStyle none
}

actor Client

node "alfresco namespace" {
    component "NGINX ingress-controller" as nginx #lightgrey
    component "Alfresco Content Services" as acs #lightgrey
    component "Alfresco Search Services" as ass #lightgrey
    component "Alfresco Sync Service" as sync #lightgrey
    component "PostgreSQL" as psql #lightgrey
    component "Alfresco Share" as share #lightgrey
    component "ActiveMQ" as amq #lightgrey
    rectangle "Alfresco Transform Service" {
        component "Alfresco PDF Renderer" as pdfr #lightgrey
        component "LibreOffice" as libr #lightgrey
        component "ImageMagick" as img #lightgrey
        component "Tika" as tika #lightgrey
        component "TransformMisc" as misc #lightgrey
    }
}

cloud "Amazon Web Services" {
    rectangle "GP2/3" {
        storage "EBS" as ebs1
        storage "EBS" as ebs2
        storage "EBS" as ebs3
    }
    rectangle "EFS CSI" {
        storage "EFS Volume" as vc
    }
}
Client -->> nginx

nginx -->> acs
nginx -->> share

acs -->> vc
psql -->> ebs1
ass -->> ebs2
amq -->> ebs3

ass <<->> acs
acs -->> psql
acs -->> pdfr
acs -->> libr
acs -->> img
acs -->> tika
acs -->> misc
acs <<-->> amq
share -->> acs

center footer Copyright 2021 Alfresco Software Inc

@enduml
