@startuml
!theme bluegray
Title: ACS Helm Community Deployment

skinparam componentStyle uml2
skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
    FontSize 15
    FontStyle none
    BackgroundColor Azure
}

actor Client

frame "alfresco namespace" {
    component "NGINX ingress-controller" as nginx
    component "Alfresco Content Services" as acs
    component "Alfresco Search Services" as ass
    component "PostgreSQL" as psql
    component "Alfresco Share" as share
    component "ActiveMQ" as amq
    together {
        database "Volume Claim" as vc1
        database "Volume Claim" as vc2
        database "Volume Claim" as vc3
        database "Volume Claim" as vc4
    }
    rectangle "Alfresco Transform Service" as ats {
        ' component "Transform Router" as tr
        ' component "Shared File Store" as sfs
        component "Alfresco PDF Renderer" as pdfr
        component "LibreOffice" as libr
        component "ImageMagick" as img
        component "Tika" as tika
        component "TransformMisc" as misc
    }
}

acs -[hidden]- ats
img -[hidden]- pdfr
img -[hidden]- misc

Client -->> nginx

nginx -->> acs
nginx -->> share

acs -->> vc1
amq -->> vc2
ass -->> vc3
psql -->> vc4

ass <<->> acs
acs -->> psql
acs -->> pdfr
acs -->> libr
acs -->> img
acs -->> tika
acs -->> misc
acs <<-->> amq

share -->> acs

center footer Copyright 2021 Alfresco Software Inc

@enduml
