@startuml
!theme bluegray
Title: ACS with Office Online Integration (OOI) on EKS using S3, RDS and MQ Helm Deployment Overview

skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
    FontSize 15
    FontStyle none
    BackgroungColor Azure
}

skinparam cloud {
    BorderThickness 3
    BorderColor Orange
    BackgroundColor white
    CloudFontSize 15
}

actor Client

frame "alfresco namespace" {
    component "NGINX ingress-controller" as nginx
    component "Alfresco Digital Workspace \n (with OOI config)" as adw
    component "Alfresco Content Services \n" as acs
    component "Alfresco Search Services" as ass
    component "Alfresco Sync Service" as sync
    component "Alfresco Share \n" as share
    component "Alfresco OOI Service" as ooi
    rectangle "Alfresco Transform Service" as ats {
        component "Transform Router" as tr
        component "Shared File Store" as sfs
        component "Alfresco PDF Renderer" as pdfr
        component "LibreOffice" as libr
        component "ImageMagick" as img
        component "Tika" as tika
        component "TransformMisc" as misc
    }
}

cloud "Amazon Web Services" {
    rectangle "S3 Buckets" {
        storage "ACS Contentstore" as s3acs #Orange
    }
    database "Aurora RDS" as db #Orange
    storage "EBS Volume" as ebs #Orange
    storage "EFS Volume" as vc #Orange
    queue "Amazon MQ" as mq #Orange
}

cloud "Microsoft 365" {
    storage "Auth" as msauth #DodgerBlue
    storage "Graph Files (OneDrive)" as msgraph #DodgerBlue
}

acs -[hidden]- ats
Client -->> nginx

nginx -->> acs
nginx -->> share
nginx -->> adw

ass -->> ebs
sfs -->> vc
acs -->> s3acs

ass <<->> acs
acs -->> db
acs -->> pdfr
acs -->> libr
acs -->> img
acs -->> tika
acs -->> misc
acs -->> sfs
acs <<-->> mq
tr -up->> pdfr
tr -up->> libr
tr -up->> img
tr -up->> tika
tr -up->> misc
tr <<-->> mq
pdfr -->> sfs
libr -->> sfs
img -->> sfs
tika -->> sfs
misc -->> sfs
share -->> acs
adw -->> acs
adw -->> ooi
adw -->> msauth

ooi -->> acs
ooi -->> msgraph

sync <<->> acs
sync -->> db
sync -->> mq

center footer Copyright 2021 Alfresco Software Inc

@enduml
