@startuml
!theme bluegray
Title: ACS Helm Enterprise Deployment

skinparam componentStyle uml2
skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
    FontSize 15
    FontStyle none
    BackgroundColor Azure
}

actor Client

frame "alfresco namespace" {
    component "NGINX ingress-controller" as nginx
    component "Alfresco Digital Workspace" as adw
    together {
        component "Alfresco Share" as share
        component "Alfresco Content Services" as acs
    }
    component "Alfresco Search Services" as ass
    component "Alfresco Sync Service" as sync
    component "PostgreSQL" as psql
    component "ActiveMQ" as amq
    together {
        database "Volume Claim" as vc1
        database "Volume Claim" as vc2
        database "Volume Claim" as vc3
        database "Volume Claim" as vc4
        database "Volume Claim" as vc5
    }
    rectangle "Alfresco Transform Service" as ats {
        component "Transform Router" as tr
        component "Shared File Store" as sfs
        component "Alfresco PDF Renderer" as pdfr
        component "LibreOffice" as libr
        component "ImageMagick" as img
        component "Tika" as tika
        component "TransformMisc" as misc
    }
}

acs -[hidden]- ats

Client -->> nginx

nginx -->> acs
nginx -->> share
nginx -->> adw

acs -->> vc1
ass -->> vc2
psql -->> vc3
sfs -->> vc4
amq -->> vc5

acs -->> psql
acs -->> pdfr
acs -->> libr
acs -->> img
acs -->> tika
acs -->> misc
acs -->> sfs
acs <<-->> amq
tr -->> pdfr
tr -->> libr
tr -->> img
tr -->> tika
tr -->> misc
tr <<-up->> amq
pdfr -->> sfs
libr -->> sfs
img -->> sfs
tika -->> sfs
misc -->> sfs
share -->> acs
adw -->> acs

sync <<->> acs
acs <<->> ass
sync -->> psql
sync -->> amq

center footer Copyright 2021 Alfresco Software Inc

@enduml
