version: "3"

# The acs-deployment project contains the product version of docker-compose.
#
# This version is for testing and development use. For testing and debug we need to have a more open version.
# For remote debug we need the CATALINA_OPTS and to expose port 8000.

# Add the following environment variable to CATALINA_OPTS to activate YourKit profiling agent on tomcat
#-agentpath:/usr/local/YourKit-JavaProfiler-2018.04/bin/linux-x86-64/libyjpagent.so=delay=200000,listen=all,sessionname=$$HOSTNAME,dir=/tmp/Alfresco/yourkit,onexit=snapshot,periodicperf=600,periodicmem=600,probe_off=*

services:
  alfresco:
    image: alfresco/alfresco-enterprise-repo-base:latest
    environment:
      CATALINA_OPTS : "-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
      JAVA_TOOL_OPTIONS: "
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
      "
      JAVA_OPTS :
        "
        -Dalfresco.port=8082
        -Daos.baseUrlOverwrite=http://localhost:8082/alfresco/aos
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dalfresco.restApi.basicAuthScheme=true
        -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
        -Dlocal.transform.service.enabled=false
        -Dlegacy.transform.service.enabled=false
        -Dcors.enabled=true
        -Dcors.allowed.origins=http://localhost:4200
        "
    ports:
      - 8082:8080
      - 8000:8000

  postgres:
    image: library/postgres:16.6
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    ports:
      - 5432:5432

  solr6:
    image: quay.io/alfresco/insight-engine:latest
    environment:
      #Solr needs to know how to register itself with Alfresco
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      #Alfresco needs to know how to call solr
      SOLR_SOLR_HOST: "solr6"
      SOLR_SOLR_PORT: "8983"
      #Create the default alfresco and archive cores
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      #HTTP with secret header by default
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS:
        "
        -Dalfresco.secureComms.secret=secret
        "
    ports:
      - 8083:8983 #Browser port

  activemq:
    image: alfresco/alfresco-activemq:latest
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP
