@startuml

Title: Docker Compose Deployment Overview (Enterprise)

skinparam componentStyle uml2
skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
    FontSize 15
    FontStyle none
}

actor Client

node "Docker Compose" {
    component "NGINX proxy" as proxy #lightgrey
    component "Alfresco Admin Console" as aac #lightgrey
    component "Alfresco Digital Workspace" as adw #lightgrey
    component "Alfresco Content Services" as acs #lightgrey
    component "Alfresco Search Services" as ass #lightgrey
    component "Alfresco Sync Service" as sync #lightgrey
    component "PostgreSQL" as psql #lightgrey
    component "Alfresco Share" as share #lightgrey
    component "ActiveMQ" as amq #lightgrey
    rectangle "Alfresco Transform Service" {
        component "Transform Router" as tr #lightgrey
        component "Shared File Store" as sfs #lightgrey
        component "Transform Core (AIO)" as tcore #lightgrey
    }
}

Client --> proxy

proxy --> aac
proxy --> share
proxy --> adw
proxy --> acs

share --> acs
acs <-left-> ass
sync <-left-> acs
sync --> psql
sync --> amq
acs --> psql
acs --> tcore
acs --> sfs
acs <--> amq
tr --> tcore
tr <-up-> amq
tcore --> sfs


center footer Copyright 2023 Alfresco Software Inc

@enduml
