@startuml
!theme bluegray
Title: ACS on EKS using S3, RDS, MQ & OpenSearch Helm Deployment Overview

skinparam linetype ortho

skinparam cloud {
    BorderThickness 3
    BorderColor Orange
    BackgroundColor white
    CloudFontSize 15
}

skinparam rectangle {
    BorderStyle dashed
    BackgroundColor Azure
    FontSize 15
    FontStyle none
}

actor Client

frame "alfresco namespace" {
    component "NGINX ingress-controller" as nginx
    component "Alfresco Digital Workspace" as adw
    together {
        component "Alfresco Content Services" as acs
        component "Alfresco Share" as share
    }
    rectangle "Alfresco Search Enterprise 3" as se3 {
        component "mediation" as se3mediation
        component "content" as se3content
        component "metadata" as se3metadata
        component "path" as se3path
        component "ReIndexing" as se3reidx
    }
    component "Alfresco Sync Service" as sync
    rectangle "Alfresco Transform Service" {
        component "Transform Router" as tr
        component "Shared File Store" as sfs
        component "Alfresco PDF Renderer" as pdfr
        component "LibreOffice" as libr
        component "ImageMagick" as img
        component "Tika" as tika
        component "TransformMisc" as misc
    }
}

cloud "Amazon Web Services" {
    database "Aurora RDS" as db #Orange
    storage "S3" as s3 #Orange
    storage "EFS Volume Claim" as vc #Orange
    queue "Amazon MQ" as mq #Orange
    collections "OpenSearch" as osearch #Orange
}

acs -[hidden]- se3

Client -->> nginx

nginx -->> acs
nginx -->> share
nginx -->> adw

acs -->> s3
acs -->> osearch
se3content -->> osearch
se3metadata -->> osearch
se3path -->> osearch
se3content -->> se3mediation
se3metadata -->> se3mediation
se3path -->> se3mediation
se3mediation -->> mq
se3reidx -->> db
se3reidx -->> osearch
sfs -->> vc

se3 <<-- acs
acs -->> db
acs -->> pdfr
acs -->> libr
acs -->> img
acs -->> tika
acs -->> misc
acs -->> sfs
acs <<-->> mq
tr -up->> pdfr
tr -up->> libr
tr -up->> img
tr -up->> tika
tr -up->> misc
tr <<-->> mq
pdfr -->> sfs
libr -->> sfs
img -->> sfs
tika -->> sfs
misc -->> sfs
share -->> acs
adw -->> acs

sync <<->> acs
sync -->> db
sync -->> mq

center footer Copyright 2021 Alfresco Software Inc

@enduml
