@startuml
!theme bluegray
Title: ACS Enterprise on EKS Helm Deployment Overview

skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
    FontSize 15
    FontStyle none
    BackgroundColor Azure
}

skinparam cloud {
    BorderThickness 3
    BorderColor Orange
    BackgroundColor white
    CloudFontSize 15
}

actor Client

frame "alfresco namespace" {
    component "NGINX ingress-controller" as nginx
    together {
        component "Alfresco Digital Workspace" as adw
        component "Alfresco Share" as share
    }
    component "Alfresco Content Services" as acs
    component "Alfresco Search Services" as ass
    component "Alfresco Sync Service" as sync
    component "PostgreSQL" as psql
    component "ActiveMQ" as amq
    rectangle "Alfresco Transform Service" as ats {
        component "Transform Router" as tr
        component "Shared File Store" as sfs
        component "Alfresco PDF Renderer" as pdfr
        component "LibreOffice" as libr
        component "ImageMagick" as img
        component "Tika" as tika
        component "TransformMisc" as misc
    }
}

cloud "Amazon Web Services" {
    rectangle "GP2/3" {
        storage "EBS Volume" as ebs1 #Orange
        storage "EBS Volume" as ebs2 #Orange
        storage "EBS Volume" as ebs3 #Orange
    }
    rectangle "EFS CSI" {
        storage "EFS Volume" as vc #Orange
    }
}

Client -->> nginx

nginx -->> acs
nginx -->> share
nginx -->> adw

acs -[hidden]- ats
acs -->> vc
amq -->> ebs1
psql -->> ebs2
sfs -->> vc
ass -->> ebs3

acs -->> psql
acs -->> pdfr
acs -->> libr
acs -->> img
acs -->> tika
acs -->> misc
acs -->> sfs
acs <<-->> amq
tr -->> pdfr
tr -->> libr
tr -->> img
tr -->> tika
tr -->> misc
tr <<-->> amq
pdfr -->> sfs
libr -->> sfs
img -->> sfs
tika -->> sfs
misc -->> sfs
share -->> acs
adw ->> acs

acs <<->> ass
sync <<->> acs
sync -->> psql
sync -->> amq

center footer Copyright 2021 Alfresco Software Inc

@enduml
