@startuml
!theme bluegray
Title: ACS with Intelligence Services on EKS using S3, RDS and MQ Helm Deployment Overview

skinparam componentStyle uml2
skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
    FontSize 15
    FontStyle none
    BackgroundColor Azure
}

skinparam cloud {
    BorderThickness 3
    BorderColor Orange
    BackgroundColor white
    CloudFontSize 15
}

actor Client

frame "alfresco namespace" {
    component "NGINX ingress-controller" as nginx
    together {
        component "Alfresco Digital Workspace \n (with AI config)" as adw
        component "Alfresco Share \n (with AI AMP)" as share
    }
    component "Alfresco Content Services \n (with AI AMP)" as acs
    component "Alfresco Search Services" as ass
    component "Alfresco Sync Service" as sync
    rectangle "Alfresco Transform Service" as ats {
        component "Transform Router \n (with AI config)" as tr
        component "Shared File Store" as sfs
        component "Alfresco PDF Renderer" as pdfr
        component "LibreOffice" as libr
        component "ImageMagick" as img
        component "Tika" as tika
        component "TransformMisc" as misc
        component "AI T-Engine" as aiEngine
    }
}

cloud "Amazon Web Services" {
    rectangle "S3 buckets" {
        storage "ACS" as s3acs #Orange
        storage "AI" as s3ai #Orange
    }
    database "Aurora RDS" as db #Orange
    rectangle "GP2/3" {
        storage "EBS Volume" as ebs #Orange
    }
    rectangle "EFS CSI" {
        storage "EFS Volume Claim" as vc #Orange
    }
    queue "Amazon MQ" as mq #Orange
    node "Comprehend" as comp #Orange
    node "Rekognition" as rek #Orange
    node "Textract" as tex #Orange
}

acs -[hidden]- ats
Client -->> nginx

nginx -->> acs
nginx -->> share
nginx -->> adw

ass -->> ebs
sfs -->> vc
acs -->> s3acs

ass <<->> acs
acs -->> db
acs -->> pdfr
acs -->> libr
acs -->> img
acs -->> tika
acs -->> misc
acs -->> sfs
acs <<-->> mq
tr -up->> pdfr
tr -up->> libr
tr -up->> img
tr -up->> tika
tr -up->> misc
tr -up->> aiEngine
tr <<-->> mq
pdfr -->> sfs
libr -->> sfs
img -->> sfs
tika -->> sfs
misc -->> sfs
share -->> acs
adw -->> acs

sync <<->> acs
sync -->> db
sync -->> mq

aiEngine -->> sfs
aiEngine -->> s3ai
aiEngine -->> comp
aiEngine -->> rek
aiEngine -->> tex

center footer Copyright 2021 Alfresco Software Inc

@enduml
