---
name: Bump versions
run-name: Bump ${{ inputs.update-type }}${{ inputs.update-type == 'values' && format(' using alfresco-updatecli/{0}', inputs.alfresco-updatecli-ref || 'master') || '' }}

on:
  push:
    paths:
      - .github/workflows/bumpVersions.yml
      - docker-compose/updatecli-matrix-targets.yaml
      - helm/*/updatecli-matrix-targets.yaml
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:
    inputs:
      update-type:
        description: 'Which dependencies to bump'
        type: choice
        options:
        - charts
        - values
        - all
      alfresco-updatecli-ref:
        description: "The version to use for alfresco/alfresco-updatecli configs (only for values update-type)"
        type: string
        default: master
  workflow_call:
    inputs:
      update-type:
        type: string
        required: true
      alfresco-updatecli-ref:
        type: string
        default: master
    secrets:
      GH_APP_ENGINEERING_RO_PRIVATE_KEY:
        required: true
      QUAY_USERNAME:
        required: false
      QUAY_PASSWORD:
        required: false

permissions:
  contents: write

jobs:
  bump-charts-dependencies:
    runs-on: ubuntu-latest
    name: Helm charts dependencies
    if: inputs.update-type == 'charts' || inputs.update-type == 'all'
    env:
      USE_DEDICATED_BRANCH: ${{ inputs.update-type == 'all' || github.ref_name == 'master' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Install Updatecli
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-updatecli@v18.12.0

      - run: updatecli pipeline apply

      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v18.12.0

      - name: Regenerate helm docs if necessary
        uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v18.12.0
        with:
          pre-commit-args: helm-docs || true
          skip_checkout: "true"

      - name: Create or reset target branch
        if: github.actor != 'dependabot[bot]' && env.USE_DEDICATED_BRANCH == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
          BRANCH: updatecli-bump-helm
        run: |
          git checkout -b "${{ env.BRANCH }}"
          git push --force origin "${{ env.BRANCH }}"

      - name: Commit changes
        if: github.actor != 'dependabot[bot]'
        uses: iarekylew00t/verified-bot-commit@5b4e8852dc472093935b8debcb81459bb79f7986  # v2.3.2
        with:
          ref: refs/heads/${{ env.USE_DEDICATED_BRANCH == 'true' && 'updatecli-bump-helm' || github.ref_name }}
          files: |
            helm/**
          if-no-commit: info
          message: |
            🛠 Updatecli pipeline charts bump

  bump-values-dependencies:
    runs-on: ubuntu-latest
    name: Image tags values dependencies
    if: (inputs.update-type == 'values' || inputs.update-type == 'all' || github.event_name == 'push') && github.actor != 'dependabot[bot]'
    env:
      USE_DEDICATED_BRANCH: ${{ inputs.update-type == 'all' || github.ref_name == 'master' }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Install Updatecli
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-updatecli@v18.12.0

      - name: Checkout updatecli configs
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          repository: alfresco/alfresco-updatecli
          ref: ${{ inputs.alfresco-updatecli-ref || 'master' }}
          path: alfresco-updatecli

      - name: Generate engineering read-only app token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1  # v3.2.0
        with:
          client-id: ${{ vars.GH_APP_ENGINEERING_RO_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_ENGINEERING_RO_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          permission-contents: read

      - name: Build manifest and run Updatecli pipelines
        shell: bash
        run: |
          for i in {docker-compose,helm/*}/updatecli-matrix-targets.yaml; do
             TARGET=$(basename $(dirname $i))
             echo -e "\n###### Building Updatecli manifest for ${TARGET}\n"
             updatecli pipeline apply -c alfresco-updatecli/deployments/uber-manifest.tpl -v alfresco-updatecli/deployments/values/supported-matrix.yaml -v ${i}
          done
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          UPDATECLI_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v18.12.0
      - name: Regenerate helm docs if necessary
        uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v18.12.0
        with:
          pre-commit-args: helm-docs || true
          skip_checkout: "true"

      - name: Create target branch
        if: env.USE_DEDICATED_BRANCH == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
          BRANCH: updatecli-bump-acs
        run: |
          git checkout -b "${{ env.BRANCH }}"
          git push --force origin "${{ env.BRANCH }}"

      - name: Commit changes
        uses: iarekylew00t/verified-bot-commit@5b4e8852dc472093935b8debcb81459bb79f7986  # v2.3.2
        with:
          ref: refs/heads/${{ env.USE_DEDICATED_BRANCH == 'true' && 'updatecli-bump-acs' || github.ref_name }}
          files: |
            helm/**
            docker-compose/**
          if-no-commit: info
          message: |
            🛠 Updatecli pipeline values bump
