---
name: Docker Compose (Community)

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    branches:
      - master
      - release/**
      - next/**
    paths:
      - docker-compose/community-compose.yaml
      - docker-compose/commons/**
      - test/postman/docker-compose/**
      - .github/workflows/docker-compose-community.yml
  push:
    branches:
      - master
      - release/**

jobs:
  compose_community:
    name: Docker Compose community
    runs-on: ubuntu-latest
    if: >-
      github.event_name != 'pull_request_review'
      || (
        github.event_name == 'pull_request_review'
        && github.event.review.state == 'approved'
        && github.event.pull_request.user.login == 'github-actions[bot]'
      )
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: >-
          Alfresco/alfresco-build-tools/.github/actions/dbp-charts/verify-compose@v18.15.0
        with:
          compose_file_path: docker-compose/community-compose.yaml
          postman_path: test/postman/docker-compose
          postman_json: acs-test-docker-compose-collection.json
