---
name: Release Download trials

on:
  workflow_dispatch:

env:
  DEFAULT_BRANCH_NAME: master
  TRIALS_BRANCH_NAME: download-trial

jobs:
  create_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Create PR for download trials
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          ref: ${{ env.DEFAULT_BRANCH_NAME }}

      - name: Generate Download trial compose files
        working-directory: docker-compose
        run: |
          docker compose -f compose.yaml config -o docker-compose.yml
          docker compose -f community-compose.yaml config -o community-docker-compose.yml

      - name: Set Commit Branch Name
        id: set_commit_branch_name
        run:
          echo COMMIT_BRANCH_NAME=download-trial-release-${{ github.run_id }} >> $GITHUB_OUTPUT

      - name: Create draft PR
        id: pr
        env:
          GH_TOKEN: ${{ github.token }}
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ github.token }}
          branch: ${{ steps.set_commit_branch_name.outputs.COMMIT_BRANCH_NAME }}
          base: ${{ env.TRIALS_BRANCH_NAME }}
          draft: true
          commit-message: "🛠 Update download trial compose files"
          add-paths: |
            docker-compose/docker-compose.yml
            docker-compose/community-docker-compose.yml
          body: |
            This PR updates the download trial compose files served by the Download Trials service.

            Pay attention to using the Docker compose short syntax for:
              * [ports](https://docs.docker.com/reference/compose-file/services/#short-syntax-3)
              * [volumes](https://docs.docker.com/reference/compose-file/services/#short-syntax-5)
            The download trial service cannot parse the long syntax and will fail.
          author: github-actions[bot]
          team-reviewers: Alfresco/alfresco-ops-readiness
          sign-commits: true
