name: kics

on:
  pull_request:
    branches: [master]
    paths:
      - 'docker-compose/**'
      - 'helm/**'
      - '.github/workflows/kics.yml'
  push:
    branches: [master]
    paths:
      - 'docker-compose/**'
      - 'helm/**'
      - '.github/workflows/kics.yml'

permissions:
  security-events: write

jobs:
  kics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: run kics Scan
        uses: checkmarx/kics-github-action@05aa5eb70eede1355220f4ca5238d96b397e30a6 # v2.1.20
        with:
          path: 'docker-compose,helm'
          ignore_on_exit: results
          output_path: report-dir/
          output_formats: 'sarif'
          token: ${{ secrets.GITHUB_TOKEN }}
          enable_jobs_summary: true
          platform_type: 'dockercompose,kubernetes'
          disable_secrets: true
          config_path: .github/kics.yml
      - name: Upload SARIF file
        if: github.actor != 'dependabot[bot]'
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
        with:
          sarif_file: report-dir/results.sarif
