---
name: Pre-commit (Helm)

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    branches:
      - master
      - release/**
      - next/**
    paths:
      - helm/**
      - test/postman/helm/**
      - .github/workflows/pre-commit-helm.yml
      - "**.md"
      - .pre-commit-config.yaml
  push:
    branches:
      - master
      - release/**

env:
  # https://pre-commit.com/#temporarily-disabling-hooks
  SKIP: docker-compose-check

jobs:
  pre_commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    if: >-
      github.event_name != 'pull_request_review'
      || (
        github.event_name == 'pull_request_review'
        && github.event.review.state == 'approved'
        && github.event.pull_request.user.login == 'github-actions[bot]'
      )
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # 6.0.3
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-helm-docs@v18.7.0
      - name: Add dependency chart repos
        run: |
          for repo in $(yq eval-all \
          '. as $item ireduce ({}; . *+ $item ) | [.dependencies[].repository | select(. == "http*")] | unique | .[]' \
          ./helm/*/Chart.yaml); do repo_name=$(echo "$repo" | awk -F/ '{print $3}')
            helm repo add "$repo_name" "$repo"
          done

      - name: Run  Pre-commit hooks
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
